feat(form): implement FormControl and ControlConfig prop `triggerValidationOn`
ayoayco/astro-reactive-library pull request #224
Opened 2022-12-03 05:50 UTC by alexsam29

## feat(form): implement FormControl and ControlConfig prop triggerValidationOn

Fixes #201 

Description of changes: 
- Created a new type in [validator.types.ts](https://github.com/alexsam29/astro-reactive-library/blob/9ee7442b389207960ab0b14c354bbd8d2cecac63/packages/common/types/validator.types.ts#L3) called `ValidationHooks`.
    - This is used to define different types of event listeners. I only added 3 basic ones (`blur`, `keypress`, and `click`), but more can and should be added.
- Added a new attribute to the interface `ControlBase` in [control.types.ts](https://github.com/alexsam29/astro-reactive-library/blob/9ee7442b389207960ab0b14c354bbd8d2cecac63/packages/common/types/control.types.ts#L40) called ` triggerValidationOn`
    - This will hold the user specified event listener
- Added an additional class variable in [FormControl](https://github.com/alexsam29/astro-reactive-library/blob/9ee7442b389207960ab0b14c354bbd8d2cecac63/packages/form/core/form-control.ts#L29) called ` _triggerValidationOn`.
    - The user specified event listener will be assigned to this variable to use in the `<input>` elements.
- Added a data attribute called `data-validation-on` in [input.astro](https://github.com/alexsam29/astro-reactive-library/blob/9ee7442b389207960ab0b14c354bbd8d2cecac63/packages/form/components/controls/Input.astro#L49) to hold  the user specified event listener type. Will be `null` is no type is specified.
- Adjusted [Validator.astro](https://github.com/alexsam29/astro-reactive-library/blob/9ee7442b389207960ab0b14c354bbd8d2cecac63/packages/validator/Validator.astro#L34) to use the data attribute `valaidationOn` to get the event listener type from `<input>` elements.

Notes:
- Demo pages now need to be adjusted to specify event listener types. Since the default is `null` if nothing is specified, there's no validation anymore.
- As mentioned, need to add more event listener types. Since there's a lot, I'm not sure what we consider "crucial" to add.

Let me know if any adjustments are needed. I can also fix the demo pages and add more event listener types in the same PR, if necessary.

Tag a reviewer: @ayoayco 

Tasks:
- [x] I have ran the build command to make sure apps are working: `npm run build`
- [x] I have ran the tests to make sure nothing is broken: `npm run test`
- [x] I have ran the linter to make sure code is clean: `npm run lint`
- [x] I have reviewed my own code to remove changes that are not needed

2022-12-03 07:16 UTC, ayoayco commented
Let's keep onBlur as default so the existing demos and examples are still supported for now. @alexsam29

2022-12-03 18:25 UTC, Icyscools requested changes
Great! I like your idea to check which events are used to trigger validation. 👍🏽 

However, I have a request change about a default value which @ayoayco commented. Also, I think this solution only works with the `Input.astro`, so we should open a new issue for other components (RadioGroup, TextArea) to work with this feature later.

2022-12-03 18:25 UTC, Icyscools commented on packages/form/core/form-control.ts
> +			triggerValidationOn = '',
As @ayoayco said, this `triggerValidationOn` should have a `blur` value as default.

2022-12-03 21:30 UTC, alexsam29 commented
> Also, I think this solution only works with the `Input.astro`, so we should open a new issue for other components (RadioGroup, Dropdown, and TextArea) to work with this feature later.

This can work with `RadioGroup` as well since it uses the `<input>` element. All that needs to be added is the `data-validation-on` data attribute.

If we want the other components to work, in `Validator.astro` we can select all elements on the page and just add an event listener for whatever element contains the data attribute `data-validation-on`

2022-12-03 21:32 UTC, ayoayco commented
Yeah, I think we can have a selector using the attribute instead of the element name. That's a good approach 👌

2022-12-03 21:39 UTC, Icyscools commented
> This can work with `RadioGroup` as well since it uses the `<input>` element. 

Oh, my mistake 😅 Yes, you're right.

> If we want the other components to work, in `Validator.astro` we can select all elements on the page (instead of just `form input` like we do now) and just add an event listener for whatever element contains the data attribute `data-validation-on`

That's sound goods!

2022-12-04 19:08 UTC, Icyscools requested changes
Nice! Now it supports every component that we supported now except only RadioGroup. I have pulled your branch to test on my local. Only RadioGroup isn't working with this config.

```js
{
  name: "rating",
  label: "Rating",
  type: "radio",
  validators: [Validators.required],
  triggerValidationOn: "click",
  options: ["1", "2", "3", "4", "5"],
}
```
(note: `Validators` is imported from `@astro-reactive/validator`.)

However, in this case, If you think it is out of scope, we can open a new issue for it. 👀 
Also, I have reviewed and have some suggestions for your code. Please, have a look. 😄

2022-12-05 05:53 UTC, alexsam29 commented on packages/validator/Validator.astro
> +		if (input.dataset.validationOn) {
Done. It works without the condition and only selects the ones with the attribute. But now there's a lint error that says `validationOn` is an undefined type, which goes away when adding back the condition.

2022-12-05 06:04 UTC, alexsam29 commented
> Nice! Now it supports every component that we supported now except only `RadioGroup`. I have pulled your branch to test on my local. Only `RadioGroup` isn't working with this config.
> 
> ```js
> {
>   name: "rating",
>   label: "Rating",
>   type: "radio",
>   validators: [Validators.required],
>   triggerValidationOn: "click",
>   options: ["1", "2", "3", "4", "5"],
> }
> ```

@Icyscools  Hmmm... What do you mean it doesn't work? The attribute doesn't change to `click`? I tried this configuration and the attribute's value is `click` and the validator gives `false` values to the other attributes:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/69481177/205561015-a21abf0b-3faf-411c-b5c3-c59bb8f97b63.png">

2022-12-05 14:02 UTC, Icyscools commented
> > Nice! Now it supports every component that we supported now except only `RadioGroup`. I have pulled your branch to test on my local. Only `RadioGroup` isn't working with this config.
> > ```js
> > {
> >   name: "rating",
> >   label: "Rating",
> >   type: "radio",
> >   validators: [Validators.required],
> >   triggerValidationOn: "click",
> >   options: ["1", "2", "3", "4", "5"],
> > }
> > ```
> 
> @Icyscools Hmmm... What do you mean it doesn't work? The attribute doesn't change to `click`? I tried this configuration and the attribute's value is `click` and the validator gives `false` values to the other attributes: <img alt="image" width="305" src="https://user-images.githubusercontent.com/69481177/205561015-a21abf0b-3faf-411c-b5c3-c59bb8f97b63.png">

Sorry! I didn't give you all of the information. My bad 😅.  You have to set a `validateOnLoad` in `Form.astro` to see through the problem.
```js
// check on apps/demo/src/index.astro
<Layout title={title} theme={theme}>
  <Form showValidationHints={true} formGroups={form} theme={theme} validateOnLoad={true} />
</Layout>
```
With a `validateOnLoad` property, the form will validate from the server side. In another word, if we open it through the browser, we'll see a form with server-side validation. (yes, this is the power of Astro 🤣)

Back to our problem, the `RadioGroup` with a required validation should need to check if a radio group has a checked mark on any options. However, it doesn't work with the current solution right now, since the validator will do client-side validate every form control one by one.

![image](https://user-images.githubusercontent.com/30778789/205655697-f1c84175-2a6d-498f-acd6-a45a65692951.png)

2022-12-06 11:40 UTC, Icyscools approved these changes
LGTM! 🚀

2022-12-06 11:43 UTC, ayoayco commented
Thanks @Icyscools and @alexsam29 for iterating on this! Just mention this PR as well in the new issue so there is continuity in the discussion. I think this is safe to be merged @Icyscools 🚀

2022-12-06 11:44 UTC, merged