chore: create script for updating RELEASE.md before PR
ayoayco/astro-reactive-library pull request #232
Opened 2022-12-09 03:33 UTC by NeilAn99

## chore: create script for updating RELEASE.md before PR

Fixes #148 

Description of changes: 
- Added the [prompt-sync](https://www.npmjs.com/package/prompt-sync) and [semver](https://www.npmjs.com/package/semver) packages.
- Created a script `pr-updater.js` located in the `packages` directory that can be run using `npm run release`. This script will prompt the contributor for the package changed, the type of PR, and the description(s) of changes made. Then, the script will find the corresponding RELEASE.md file and update it.

For example, the running the script:
![image](https://user-images.githubusercontent.com/54966170/206618095-687c8b71-16a9-4be8-a570-30e288281baa.png)
Will produce the following RELEASE.md:
![image](https://user-images.githubusercontent.com/54966170/206618219-07ac7f54-3010-45fd-b31c-c57665c1301e.png)

Tag a reviewer: @ayoayco 

Tasks:
- [x] I have ran the build command to make sure apps are working: `npm run build`
- [x] I have ran the tests to make sure nothing is broken: `npm run test`
- [ ] I have ran the linter to make sure code is clean: `npm run lint`
- [x] I have reviewed my own code to remove changes that are not needed

2022-12-09 10:51 UTC, Icyscools requested changes

2022-12-09 20:23 UTC, ayoayco commented on packages/pr-updater.js
> +    }
Yeah, switch-case makes sense here, then maybe a `default` case to throw an error or loop through the question again after a message "Invalid option"

2022-12-09 20:26 UTC, ayoayco reviewed
Thanks @NeilAn99, this is great progress for the project. We want to get this in! Can you go through a couple of suggestions first?

2022-12-09 20:33 UTC, ayoayco commented
Oh and one very important thing I missed: the package.json "version" property in the package needs to be updated to the same as the version that is written to the RELEASE.md. @NeilAn99

2022-12-09 22:50 UTC, ayoayco commented on packages/pr-updater.js
> +
@Fawrish#0487 you can remove adding the version for now in your script. Just focus on the change and type. Where the type could either be "fix" or "feature"

So no need to add the big text for version but just items like:

Features
- Feature description text

Fixes
- Change description text
- dix description 2

2022-12-10 08:28 UTC, NeilAn99 commented
I have updated the code so that it doesn't deal with versioning, added some input checking and focused on features/fixes. Now running the script will look like:
![image](https://user-images.githubusercontent.com/54966170/206840895-9e2a292b-cc8c-4a29-8eb4-0d11ece596c4.png)
and will produce:
![image](https://user-images.githubusercontent.com/54966170/206841073-3d1cc361-d2d1-4e12-a753-f5de5a05f84a.png)
Multiple updates to the same package will look like:
![image](https://user-images.githubusercontent.com/54966170/206841090-b94599ae-7ef7-489c-9ec3-cb935c4d9973.png)
Is this acceptable? @Icyscools @ayoayco

2022-12-10 18:28 UTC, Icyscools approved these changes
LGTM! 🚀 However, please fix a conflict on a `package.json`. I think it was a line in the `publish` script. Make sure to use it from our latest main branch and it'll be safe to merge. 🦺

2022-12-11 17:35 UTC, Icyscools approved these changes

2022-12-16 12:43 UTC, ayoayco commented
Thanks @Icyscools and @NeilAn99 -- I'm merging this now! :)

2022-12-16 12:43 UTC, merged